---
- name: starting MySQL database server installation and configuration bunch of tasks
  hosts: db
  vars_files:
    - ./group_vars/vault
  tasks:
  - name: installing mariadb
    package:
      name: "{{ item }}"
      state: present
    loop:
      - mariadb-server
      - MySQL-python.x86_64 ## without this shit ansible not able to manage mysql
  - name: starting mariadb server service
    service:
      name: mariadb
      state: started
      enabled: true
  - name: creating wordpress database
    mysql_db:
      name: "{{ DB_NAME }}"
      state: present
  - name: creating wordpress user
    mysql_user:
      name: "{{ DB_USER }}"
      host: "{{ WEB_HOST }}"
      password: "{{ DB_PASSWORD }}"
      priv: "{{ DB_NAME }}.*:ALL"